/* Generated By:JavaCC: Do not edit this line. ParserCennikaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserCennikaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DELIMITER = 5;
  /** RegularExpression Id. */
  int DATE_LABEL = 6;
  /** RegularExpression Id. */
  int GROUP_LABEL = 7;
  /** RegularExpression Id. */
  int PRODUCT_LABEL = 8;
  /** RegularExpression Id. */
  int PROCESSOR_GROUP = 9;
  /** RegularExpression Id. */
  int MEMORY_GROUP = 10;
  /** RegularExpression Id. */
  int GRAPHIC_CARDS_GROUP = 11;
  /** RegularExpression Id. */
  int ANY = 12;
  /** RegularExpression Id. */
  int LITERY = 13;
  /** RegularExpression Id. */
  int NUMERY = 14;
  /** RegularExpression Id. */
  int ZNAKI = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"|\"",
    "\"RMD\"",
    "\"GRP\"",
    "\"PRD\"",
    "\"PROC\"",
    "\"MEM\"",
    "\"GRAPH\"",
    "<ANY>",
    "<LITERY>",
    "<NUMERY>",
    "<ZNAKI>",
  };

}
